version: '3'
services:
  employees-app-mariadb:
    image: mariadb
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: employees
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # aposztrófok nélkül boolean true-ként értelmezi
      MYSQL_USER: employees
      MYSQL_PASSWORD: employees
    ports:
      - 3308:3306

  employees-app:
    image: employees
    depends_on:
      - employees-app-mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://employees-app-mariadb:3306/employees'
      SPRING_DATASOURCE_USERNAME: 'employees'
      SPRING_DATASOURCE_PASSWORD: 'employees'
    volumes:
    - ./wait:/opt/wait
    entrypoint: ["/opt/wait/wait-for-it.sh", "-t", "120", "employees-app-mariadb:3306", "--", "java", "-jar", "employees.jar"]
    expose:
      - 8080
    ports:
      - 8082:8080
